### ISSUE TITLE
No Notification Image in Windows 10

### ISSUE THREAD

**Issue by innesst** [OrangeDrangon/android-messages-desktop#189]
**Describe the bug**
When a notification comes through, the letter of the person's name is shown, but not their image. Also, the bottom of each notification has: "pw.kmr.android-messages-desktop" which didn't appear before

**To Reproduce**
1. Receive a text
2. View notification

**Expected behavior**
See image in the notification that appears when app is open (and don't see pw.kmr.android-....)

**Screenshots**
![image](https://user-images.githubusercontent.com/10469898/101679372-44f86180-3a2d-11eb-8401-3490fca0f647.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.3.0

**Comment by OrangeDrangon** [comment]
That looks like intended behavior. If Gary had a profile image it would be their instead of the icon. The way to fetch the image is actually the same whether or not they have an image or a letter. 

The only *bug* I know of is the in memory cache that will not be refreshed until after a restart. In other words if you change the image of someone it will not change in notifications until after a restart.

**Comment by vanowm** [comment]
The "letter" avatar shown while actual avatar has not downloaded yet. The app itself is caching avatars, which means that on slow connection it might cache the "letter" avatar.
Caching avatars should be removed, it doesn't provide any benefits see benchmark in #235.
