### ISSUE TITLE
Should there be an auto updater?

### ISSUE THREAD

**Issue by OrangeDrangon** [OrangeDrangon/android-messages-desktop#291]
There have been some murmurs of dislike over the current implementation of the auto updater (a feature I have not worked on or personally use).

Should it be removed until I can dedicate time to put some work into it?

Please vote with the reactions.

**Comment by innesst** [comment]
I think not. You indicate for 4.2.0 that the project is feature complete. So updates are really only when things are really broken and it's not working at all. If you disable auto update, a person's current version will update to the version without auto-update, and sooner or later something will break (sooner knowing google), and they might be stuck trying to figure it out. With auto update, they at least should get the repaired version before too long.

**Comment by vanowm** [comment]
Currently there are two issues with it:

1. it checks for update on every launch, hens showing popups every launch
2. it installs update as "regular" version even if portable version used, making it useless.

I think if a delay between notifications for the same version was implemented, let's say a week, it would definitely help. 
Or show something inside the window, when an update is available instead of popups.
Also, there is "check for updates" option in help menu, so if something goes wrong, people always can use it to manually check for updates.

P.S.
You are not using auto update, because your version is always up-to-date, obviously...lol

**Comment by OrangeDrangon** [comment]
> You are not using auto update, because your version is always up-to-date, obviously...lol

I am not using auto update because I use linux. Specifically a version from the AUR whose packaging I do not maintain so it is not always up to date but he is scary quick at releasing the new version....

**Comment by OrangeDrangon** [comment]
After some research it looks like it should be pretty trivial to get a user dialog going for the auto update to avoid unexpected problems.
