### ISSUE TITLE
Emoji not visible in chats, but are visible on chat list column on left

### ISSUE THREAD

**Issue by kevev** [OrangeDrangon/android-messages-desktop#425]
~~5.4.1 seems to have caused this.~~
Seems to be a Google change as stated below.

**Comment by prisoner881** [comment]
Also seeing this same behavior.

**Comment by ikeeki320** [comment]
I went to Messages for Web in Chrome and saw that some of the emojis, like thumbs up and rolling laughing, are now animated. It appears that this new feature may be the culprit as to why they aren't showing up in the message window, but still show up in the left side message list.

**Comment by OrangeDrangon** [comment]
I will give this a look this weekend hopefully.

Thanks
Kyle

**Comment by innesst** [comment]
Single animated emojis that are blank in the app appear properly as static images in the Windows notification pop up.

**Comment by OrangeDrangon** [comment]
Alright I was able to reproduce this.

**Comment by kevev** [comment]
> Alright I was able to reproduce this.

Any progress?  :)

**Comment by gregeeh** [comment]
I too have this issue.  Any progress?

**Comment by tbarnettsgf** [comment]
Is this something that is going to be fixed?  thx

**Comment by agottschling** [comment]
Still seeing this. My account recently got the animated emojis

**Comment by mhoffmeyerDC** [comment]
It looks like the root cause is how the Lottie Library, which is loaded dynamically on chats with emoji, is registering itself. 

Since nodeIntegration is true, module.exports is provided as a global but when lottie loads itself its registering with the node process instead of the renderer. 

As a quick hack I set `window,module.exports = null` in `bridge.ts` and viola, that forces the lottie library to register to the window object instead and all the animations showed up. Manualy pasting in the contents of https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.12.2/lottie.min.js into the console without any modifications to the source code also caused the emoji to show properly.

Not sure what the best way to fix it long term would be but that's at least the root cause of the problem.

**Comment by OrangeDrangon** [comment]
Thanks for this investigation. I will stew on something.

Thanks
Kyle

**Comment by dmyurych** [comment]
Just wanted to add that this is not a Windows only issue and also appears for me on MacOS

**Comment by LarveyOfficial** [comment]
@mhoffmeyerDC for your fix, did you just add
`window.module.exports = null`
next to `window.Notification.permission = "granted";`
in bridge.ts?

**Comment by mhoffmeyerDC** [comment]
Yup, just added it at the end of bridge.ts. I'm looking at my changes and I had also set `webSecurity: false,` within `webPreferences` on `background.ts` not sure if that has any effect or not.

**Comment by LarveyOfficial** [comment]
@mhoffmeyerDC Thanks a bunch, I will look into this for my fork.

**Comment by LarveyOfficial** [comment]
@kevev my branch has this implementation
https://github.com/LarveyOfficial/google-messages-desktop

**Comment by OrangeDrangon** [comment]
PR?

**Comment by kevev** [comment]
Still hoping for a build.  :)

**Comment by OrangeDrangon** [comment]
It is building rn

**Comment by OrangeDrangon** [comment]
Published
